drop table if exists menu CASCADE;
create table menu
(
 day bigint generated by default as identity,
 d_menu varchar(255) NOT NULL,
 primary key (day)
);

insert into menu(day,d_menu)
values
(2,'흑기장밥 , 애호박된장찌개 , *수육 , 다시마부각 , 보쌈김치 , 청포도 , *청상추쌈/쌈장'),
(3,'*탕국 , *헛제사비빔밥+양념장 , *눈꽃로제돈까스/소스 , *함초김 , 배추김치 , 대추방울토마토'),
(4,'*기장밥 , 양지쌀국수 , *돈마호크 , 배추김치 , *체리 , *스트로베리우유'),
